# Generated by Django 5.0.6 on 2024-06-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_statusfile_options_alter_statusfile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusfile',
            name='is_proccessed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='statusfile',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'قبول'), ('2', 'رفض'), ('3', 'تعديل'), ('4', 'تم التحقق')], max_length=25, null=True),
        ),
    ]
