# Generated by Django 5.0.6 on 2024-06-17 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_statusfile_is_proccessed_alter_statusfile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusfile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='statusfile',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'طلب مراجعة مشرف'), ('2', 'طلب تعديل من مساعد'), ('3', 'رفض'), ('4', 'طلب مراجعة مدير'), ('5', 'تم التحقق')], max_length=25, null=True),
        ),
        migrations.CreateModel(
            name='OrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
